# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a78387c424d280ced1c6f05bfa6f4346246622f33a47a6092b4b3819a08d8fceec555eba4a15c8383c7f899c2f7aee1cab611cee3eb3bb44c9a0502cf3b1bc8

test:
  secret_key_base: b869abdce939f4606bd89f2776936859aa65ee1ba78fbcadaa531a926ba1a7bd422956e1b2c8eab59dcc83cc4e32b0aeb4f5c1d6c81cb3682225b4cf1eb6d888

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
